<div style="background-color: #d1e7dd; padding: 20px; border-radius: 10px;">
        <h1 style="color: #000000;"><b>PRUEBA 1 - SOLUCIÓN</h1>
        <h3 style="color: #000000;">Fundamentos 2024 II </h3>
        <p style="font-size: 18px; color: #000000;">
            <b>INTEGRANTES:</b><br>
           
        Cristian Jiménez         CC 1020460089
        Juan Felipe Quinto Rios  CC 1041152117
        Veronica Arango Toro     CC 1039473234



# **Prueba \#1**

En la siguiente pureba se evalua de manera EXCLUSIVA lo que se solicita, cualquier otra respuesta adicional a ella será valorada, más no evaluada. Entregue la prueba en un repositorio de github, o en el classroom antes de el lunes 12 de Agosto a las 00:00:00.

**Incluya como encabezado los nombres de los participantes y las cédulas**



---

## **Ejercicio 1** (50 pts)

Escriba una clase `Pedido` que pueda ser usada para gestionar la información de los pedidos realizados a una pastelería (o carnicería o tienda de ropa o empresa que ud desee). Evite usar módulos como numpy, pandas o cualquier otro.

### **Rubrica**:

1. Generación de la clase que funcione correctamente con al menos 2 métodos y 2 atributos. **30 pts**.
2. Comentarios y  documentación que sirva para quien deba usar la clase. **5 pts**.
3. Pertinencia de la clase en el ámbito, ¿Por qué será útil esta herramienta y cómo ayudará a mejorar el negocio? esta será entregada en una celda de texto. **10 pts**.
4. ¿Cree que se pueda construir una clase hija que ayude al proceso? Si sí constrúyala, sino, argumente por qué en una célda de código. **5 pts**.

----

### **Solución Ejercicio 1**

In [1]:
class Pedido:
    def __init__(self, producto: str, cantidad: int, precio_unitario: float, nombre_cliente: str, cedula_cliente: int, fecha_pedido: str, hora_pedido: str):
        """
        Constructor padre -  clase Pedido.

        Parámetros:
        producto (str): Nombre del producto.
        cantidad (int): Cantidad de productos solicitados.
        precio_unitario (float): Precio unitario del producto.
        nombre_cliente (str): Nombre del cliente que realiza el pedido.
        cedula_cliente (int): Cédula del cliente.
        fecha_pedido (str): Fecha en la que se realiza el pedido (formato 'YYYY-MM-DD').
        hora_pedido (str): Hora en la que se realiza el pedido (formato 'HH:MM').
        """
        self.producto = producto
        self.cantidad = cantidad
        self.precio_unitario = precio_unitario
        self.nombre_cliente = nombre_cliente
        self.cedula_cliente = cedula_cliente
        self.fecha_pedido = fecha_pedido
        self.hora_pedido = hora_pedido

    def calcularTotal(self):
        """
        Est función calcula el total del pedido.

        Retorna:
        float: El total del pedido, calculado como la cantidad por el precio unitario.
        """
        return self.cantidad * self.precio_unitario

    def codigoPedido(self):
        """
        Genera un código único para el pedido basado en la cédula del cliente, 
        la fecha del pedido y la hora del pedido.

        Retorna:
        str: Código único del pedido.
        """
        return str(self.cedula_cliente) + str(self.fecha_pedido) + str(self.hora_pedido)

class Factura(Pedido):
    def __init__(self, factura, producto: str, cantidad: int, precio_unitario: float, nombre_cliente: str, cedula_cliente: int, fecha_pedido: str, hora_pedido: str):
        """
        Constructor de la clase Factura, que hereda de la clase Pedido.

        Parámetros:
        factura: Parámetro no utilizado en la implementación actual.
        (El resto de parámetros son heredados de la clase Pedido)
        """
        Pedido.__init__(self, producto, cantidad, precio_unitario, nombre_cliente, cedula_cliente, fecha_pedido, hora_pedido)
        self.factura = {
            "codigo_pedido": self.codigoPedido(),
            "producto": producto,
            "cantidad": cantidad,
            "total": self.calcularTotal(),
            "precio_unitario": precio_unitario,
            "nombre_cliente": nombre_cliente,
            "cedula_cliente": cedula_cliente
        }

    def generarFactura(self):
        """
        Genera una factura como un diccionario con los detalles del pedido.

        Retorna:
        dict: Diccionario que contiene los detalles de la factura, como el código del pedido,
              producto, cantidad, total, precio unitario, nombre del cliente y cédula del cliente.
        """
        return self.factura

    def imprimirFactura(self):
        """
        Imprime los detalles de la factura en la consola.
        """
        print(self.factura)


Para probar la funcionalida de la clase insertamos los atributos bajo el contexto de un panaderia. Posteriormente llamamos a los metodos contenidos dentro de esta clase verificando su funcionalidad 


In [2]:
pedido1 = Pedido("Almojábana", 4, 2000, "Juan Felipe", 1234, "1008", "1410")

In [3]:
pedido1.calcularTotal()

8000

In [4]:
pedido1.codigoPedido()

'123410081410'

Ahora bien, hacemos uso de la subclase e insertamos el valor del atributo; Posteriormente mandamos invocamos al metodo contenido en esta que nos permite imprimir los atributos contenidos en la factura

In [5]:
factura1 = Factura(1, "Almojábana", 4, 2000, "Juan Felipe", 1234, "1008", "1410")

In [6]:
factura1.imprimirFactura()

{'codigo_pedido': '123410081410', 'producto': 'Almojábana', 'cantidad': 4, 'total': 8000, 'precio_unitario': 2000, 'nombre_cliente': 'Juan Felipe', 'cedula_cliente': 1234}


---

## **Ejercicio 2** (50 pts)

Realice los siguientes ejercicios con numpy

1. Resolver el siguiente sistema de ecuaciones. **14 pts**

$$
2x + 3y - z + 4w + 5v = 15
$$

$$
x - 2y + 4z - 3w + v = 6
$$

$$
3x + 2y - 3z + 5w - 2v = 11
$$

$$
4x + y - 2z + 3w + 2v = 8
$$

$$
x + y + z + w + v = 7
$$

---
### **Solución Ejercicio 2:** Punto 1 

In [7]:
import numpy as np
C = np.array([[2,3,-1,4,5],[1,-2,4,-3,1],[3,2,-3,5,-2],[4,1,-2,3,2],[1,1,1,1,1]])
S = np.array([15,6,11,8,7])

In [8]:
solucion = np.linalg.solve(C,S)
solucion

array([-1.67741935, -7.87096774,  5.12903226, 10.        ,  1.41935484])

Ahora meidiante el producto punto entre `Solucion` y la matriz `C` nos debe de dar como reusltado `S`

In [9]:
S = np.dot(C, solucion)
S

array([15.,  6., 11.,  8.,  7.])

---

2. Calcule el valor del número de Euler o constante de Napier $e = 2,71828$ como:

$$e = \sum_i ^{\infty} \frac{1}{i!}$$

  ¿Qué precisión en términos de el número de términos necesita para dar cuenta de los primeros 5 números de la coma decimal? **20 pts**
  
  **Remark**: Requerirá de algo de creatividad para calcular el factorial sin el uso de ciclos for ni recursividad, siéntase libre de buscar en internet, sin embargo recuerde tratar que su cálculo sea vectorizado.

---
### **Solución Ejercicio 2:** Punto 1 

Utilizamos dos soluciones para este ejercicio; La primera (*euler1*) creando una funcion llamada factorial que permite obtener el factorial del numero; La segunda (*euler2*) solución hace uso de la libreria math, mediante la cual se emplea la función factorial contenida en la misma. 

#### Primera euler1()

In [10]:
import numpy as np

def factorial(n):
  return np.prod(np.arange(1,n+1))

def euler1(i):
  m = np.arange(0,i)
  f = np.array([factorial(n) for n in m])
  return np.sum(1/f)


In [20]:
euler1(10)

2.718281525573192

#### Segunda eurler2()

In [12]:
import numpy as np
import math

def euler2(i):
  m = np.arange(0,i)
  f = np.array([math.factorial(n) for n in m])
  return np.sum(1/f)


In [13]:
euler2(10)

2.718281525573192

En ambos casos se observa en consola que para que la función alcance los valroes  $e= 2,71828$ se debe tener un numero de $i = 10$, para que estos coincidan  

---

3. Ecuentre los auto valores y auto vectores de la matriz.  **16 pts**

$$
\begin{pmatrix}
2 & 1 & 1 \\
4 & 3 & 2 \\
1 & 1 & 2 \\
\end{pmatrix}
$$

---
### **Solución Ejercicio 2:** Punto 3 

Utilizando la librería NumPy, calculamos los autovalores y autovectores de una matriz cuadrada de la siguiente manera:

In [14]:
M = np.array([[2,1,1],[4,3,2],[1,1,2]])
autovalor, autovector = np.linalg.eig(M)

In [15]:
autovalor

array([5.44948974, 0.55051026, 1.        ])

In [16]:
autovector

array([[ 3.53553391e-01,  3.53553391e-01,  4.99600361e-16],
       [ 8.66025404e-01, -8.66025404e-01, -7.07106781e-01],
       [ 3.53553391e-01,  3.53553391e-01,  7.07106781e-01]])