Integrantes:

**Cristian Jiménez** C.C.1020460089

**Juan Felipe Quinto Rios** C.C.1041152117

**Veronica Arango Toro** C.C. 1039473234


# **Prueba \#1**

En la siguiente pureba se evalua de manera EXCLUSIVA lo que se solicita, cualquier otra respuesta adicional a ella será valorada, más no evaluada. Entregue la prueba en un repositorio de github, o en el classroom antes de el lunes 12 de Agosto a las 00:00:00.

**Incluya como encabezado los nombres de los participantes y las cédulas**



## **Ejercicio 1** (50 pts)

Escriba una clase `Pedido` que pueda ser usada para gestionar la información de los pedidos realizados a una pastelería (o carnicería o tienda de ropa o empresa que ud desee). Evite usar módulos como numpy, pandas o cualquier otro.

### **Rubrica**:

1. Generación de la clase que funcione correctamente con al menos 2 métodos y 2 atributos. **30 pts**.
2. Comentarios y  documentación que sirva para quien deba usar la clase. **5 pts**.
3. Pertinencia de la clase en el ámbito, ¿Por qué será útil esta herramienta y cómo ayudará a mejorar el negocio? esta será entregada en una celda de texto. **10 pts**.
4. ¿Cree que se pueda construir una clase hija que ayude al proceso? Si sí constrúyala, sino, argumente por qué en una célda de código. **5 pts**.

In [ ]:
class Pedido():
  def __init__(self, producto: str, cantidad: int, precio_unitario: float, nombre_cliente: str, cedula_cliente: int, fecha_pedido:str , hora_pedido:str): ##
    self.producto = producto
    self.cantidad = cantidad
    self.precio_unitario = precio_unitario
    self.nombre_cliente = nombre_cliente
    self.cedula_cliente = cedula_cliente
    self.fecha_pedido = fecha_pedido
    self.hora_pedido = hora_pedido

  def calcularTotal(self):
    return self.cantidad * self.precio_unitario

  def codigoPedido(self):
    return str(self.cedula_cliente) + str(self.fecha_pedido) + str(self.hora_pedido)

class Factura(Pedido):
  def __init__(self, factura, producto: str, cantidad: int, precio_unitario: float, nombre_cliente: str, cedula_cliente: int, fecha_pedido:str , hora_pedido:str):
    Pedido.__init__(self, producto, cantidad, precio_unitario, nombre_cliente, cedula_cliente, fecha_pedido , hora_pedido)
    self.factura ={
          "codigo_pedido": self.codigoPedido(),
          "producto": producto,
          "cantidad": cantidad,
          "total" : self.calcularTotal(),
          "precio_unitario": precio_unitario,
          "nombre_cliente": nombre_cliente,
          "cedula_cliente": cedula_cliente
      }

  def generarFactura(self):
    return self.factura

  def imprimirFactura(self):
    print(self.factura)

In [ ]:
pedido1 = Pedido("Almojábana", 4, 2000, "Juan Felipe", 1234, "1008", "1410")

In [ ]:
pedido1.codigoPedido()

'123410081410'

In [ ]:
factura1 = Factura(1, "Almojábana", 4, 2000, "Juan Felipe", 1234, "1008", "1410")

In [ ]:
factura1.imprimirFactura()

{'codigo_pedido': '123410081410', 'producto': 'Almojábana', 'cantidad': 4, 'total': 8000, 'precio_unitario': 2000, 'nombre_cliente': 'Juan Felipe', 'cedula_cliente': 1234}


## **Ejercicio 2** (50 pts)

Realice los siguientes ejercicios con numpy

1. Resolver el siguiente sistema de ecuaciones. **14 pts**

$$
2x + 3y - z + 4w + 5v = 15
$$

$$
x - 2y + 4z - 3w + v = 6
$$

$$
3x + 2y - 3z + 5w - 2v = 11
$$

$$
4x + y - 2z + 3w + 2v = 8
$$

$$
x + y + z + w + v = 7
$$

2. Calcule el valor del número de Euler o constante de Napier $e = 2,71828$ como:

$$e = \sum_i ^{\infty} \frac{1}{n!}$$

  ¿Qué precisión en términos de el número de términos necesita para dar cuenta de los primeros 5 números de la coma decimal? **20 pts**
  
  **Remark**: Requerirá de algo de creatividad para calcular el factorial sin el uso de ciclos for ni recursividad, siéntase libre de buscar en internet, sin embargo recuerde tratar que su cálculo sea vectorizado.

3. Ecuentre los auto valores y auto vectores de la matriz.  **16 pts**

$$
\begin{pmatrix}
2 & 1 & 1 \\
4 & 3 & 2 \\
1 & 1 & 2 \\
\end{pmatrix}
$$



## **Ejercicio 2** (50 pts)

Realice los siguientes ejercicios con numpy

1. Resolver el siguiente sistema de ecuaciones. **14 pts**

$$
2x + 3y - z + 4w + 5v = 15
$$

$$
x - 2y + 4z - 3w + v = 6
$$

$$
3x + 2y - 3z + 5w - 2v = 11
$$

$$
4x + y - 2z + 3w + 2v = 8
$$

$$
x + y + z + w + v = 7
$$

In [ ]:
#2x + 3y - z + 4w + 5v = 15
#x - 2y + 4z - 3w + v = 6
#3x + 2y - 3z + 5w - 2v = 11
#4x + y - 2z + 3w + 2v = 8
#x + y + z + w + v = 7

# genera una matriz con los coeficientes

import numpy as np
C = np.array([[2,3,-1,4,5],[1,-2,4,-3,1],[3,2,-3,5,-2],[4,1,-2,3,2],[1,1,1,1,1]])
S = np.array([15,6,11,8,7])

In [ ]:
solucion = np.linalg.solve(C,S)
solucion

array([-1.67741935, -7.87096774,  5.12903226, 10.        ,  1.41935484])

In [ ]:
2*-1.67741935+3* -7.87096774-  5.12903226+4* 10.        +5* 1.41935484

15.000000019999996

2. Calcule el valor del número de Euler o constante de Napier $e = 2,71828$ como:

$$e = \sum_i ^{\infty} \frac{1}{i!}$$

  ¿Qué precisión en términos de el número de términos necesita para dar cuenta de los primeros 5 números de la coma decimal? **20 pts**
  
  **Remark**: Requerirá de algo de creatividad para calcular el factorial sin el uso de ciclos for ni recursividad, siéntase libre de buscar en internet, sin embargo recuerde tratar que su cálculo sea vectorizado.

In [ ]:
import numpy as np

def factorial(n):
  return np.prod(np.arange(1,n+1))

def euler1(i):
  m = np.arange(0,i)
  f = np.array([factorial(n) for n in m])
  return np.sum(1/f)


In [ ]:
euler1(10)

2.718281525573192

In [ ]:
import numpy as np
import math

def euler2(i):
  m = np.arange(0,i)
  f = np.array([math.factorial(n) for n in m])
  return np.sum(1/f)


In [ ]:
euler2(10)

2.718281525573192

3. Ecuentre los auto valores y auto vectores de la matriz.  **16 pts**

$$
\begin{pmatrix}
2 & 1 & 1 \\
4 & 3 & 2 \\
1 & 1 & 2 \\
\end{pmatrix}
$$

In [ ]:
M = np.array([[2,1,1],[4,3,2],[1,1,2]])
autovalor, autovector = np.linalg.eig(M)

In [ ]:
autovalor

array([5.44948974, 0.55051026, 1.        ])

In [ ]:
autovector

array([[ 3.53553391e-01,  3.53553391e-01,  6.66133815e-16],
       [ 8.66025404e-01, -8.66025404e-01, -7.07106781e-01],
       [ 3.53553391e-01,  3.53553391e-01,  7.07106781e-01]])